options:
  docker: true

pipelines:
  branches:
    development:
      - step:
          script:
            # build the image
            - docker login -u $USER -p $ACCESS_TOKEN
            - docker build -t $USER/$DOCKER_REPOSITORY:latest .
            - docker push $USER/$DOCKER_REPOSITORY:latest
